### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by pharring** [pharring/EditorGuidelines#106]
Commenter Erik Martines Sanches requested an ARM version.

Documentation is here: https://learn.microsoft.com/en-us/visualstudio/extensibility/arm64/target-arm64-visual-studio-extension?view=vs-2022#add-a-visual-studio-2022-target-arm64

Looks like we just have to update the extension manifest.

**Comment by pharring** [comment]
I can add the manifest, but I don't have access to an ARM box to test it.

**Comment by erikmartinessanches** [comment]
It's working, thanks.

**Comment by erikmartinessanches** [comment]
Ok it worked on the VS2022 _Preview_. However, I'm unable to installing on the regular VS2022 Microsoft Visual Studio Enterprise 2022 (ARM 64-bit) - Current Version 17.4.3.

**Comment by pharring** [comment]
That's because you're trying to install the VS 2019 version.
Install this one: https://marketplace.visualstudio.com/items?itemName=PaulHarrington.EditorGuidelinesPreview
(I know it has "Preview" in the name)
This is because we have to have separate VSIX's for VS 2019 and VS 2022 and the Marketplace doesn't support multiple VSIX's in a single listing.
