### ISSUE TITLE
VS 2019 startup the 'Visual Studio Common IDE Package' package did not load correctly. Project no load in at all

### ISSUE THREAD

**Issue by FTApp1998** [pharring/EditorGuidelines#114]
Hi , request help and advise on this matter.
have uninstall vs 2019 several time. 
study the log.xml and found be exception 

SetSite failed for package [Visual Studio Common IDE Package]Source: &apos;mscorlib&apos; Description: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).&#x000D;&#x000A;System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).&#x000D;&#x000A;   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type)&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.PreviewFeatures.UsePreviewSdk.IsPreviewChannel()&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.PreviewFeatures.UsePreviewSdk.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.CommonIDEStatics.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.BasePackage.&lt;InitializeAsync&gt;d__6.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.CommonIDE.CommonIDEPackage.&lt;InitializeAsync&gt;d__20.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()

it happen to my VS 2022 installation, both IDE can not load project.

**Comment by pharring** [comment]
Hi @FTApp1998 ,

Sorry you're having problems with Visual Studio.
Unfortunately, I can't help you here. This repo is for the Editor Guidelines extension. From the error message, I don't think this is an Editor Guidelines issue.

It looks like a general Visual Studio problem. The CLSID 177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D is for the [SetupConfiguration](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.setup.configuration.setupconfigurationclass?view=visualstudiosdk-2022) class and Editor Guidelines doesn't use it.

Please report the problem using the [Visual Studio Feedback](https://developercommunity.visualstudio.com/home) site.

Hope you get back up and running soon.
