### ISSUE TITLE
EditorGuidelines Extension Breaks the Built-In Visual Studio Spell Checker

### ISSUE THREAD

**Issue by EWSoftware** [pharring/EditorGuidelines#116]
There seems to be a conflict between the latest Visual Studio 2022 (17.5.4) and the EditorGuidelines extension.  The extension is somehow breaking the built in Visual Studio spell checker such that it never completes and offers suggestions for misspelled words.  I also notice that this in turn can also block other code fixes as well such that they never show suggestions.

I'm the creator of the Visual Studio spell checker extension and noticed an issue in mine with the smart tags not popping up automatically anymore when you hovered the mouse over a misspelling.  Using the shortcut key to show the suggestions worked but there was always a "Loading suggestions" item at the bottom with a continuous progress bar.

Thinking the issue was in my extension I removed it and still saw similar issues with other standard code fixes not offering suggestions.     As such, I started disabling other extensions to try and track down the cause.  After disabling the EditorGuidelines extensions, everything started working again and I noticed that the built in Visual Studio spell checker was enabled and offering suggestions.  I hadn't noticed it was enabled before due to it being blocked and perhaps not enabled until this latest Visual Studio update.

After enabling the EditorGuidelines extension, the built-in spell checker suggestions went away again.  However, if I press the shortcut key to show suggestions on a misspelled word, the popup appears with the same "Loading suggestions" message and progress bar as shown below and it never completes.

![image](https://user-images.githubusercontent.com/10552523/233858585-88ba2afd-cbe8-4e75-b194-9750b3a3f243.png)

With the guidelines extension disabled, the popups work as expected in my own extension as well.  As noted, I hadn't noticed this behavior prior to the 17.5.4 update.  Also, disabling the built in Visual Studio spell checker fixes the issues as well so the conflict does appear to be with it specifically.

**Comment by pharring** [comment]
Thanks for the report. I will investigate and try to reproduce it.

**Comment by pharring** [comment]
Reproduced. Debugging.

**Comment by pharring** [comment]
The problem is with Microsoft.VisualStudio.CodingConventions
This is the assembly we use to read .editorconfig files.
The version included with EditorGuidelines (1.1.20180503.2) is incompatible with the one that ships in 17.5.4
It looks like that assembly has been de-listed from nuget.org. I need to find a replacement.

**Comment by pharring** [comment]
I think I have a fix.
We use the de-listed assembly at build time, but don't include the assembly in the VSIX. Instead, it'll be picked up from PublicAssemblies. I'm assuming that the CodingConventions assembly is available in all SKUs and all workloads.

**Comment by pharring** [comment]
I think it's fixed. I will try to get a new release published tomorrow.

**Comment by prlcutting** [comment]
As a user of both the Editor Guidelines and Spell Checker extensions, I noticed the same behavior recently, but had no idea what the cause was. Thank you for the rapid fix.

And thank you both for the fantastic extensions that you maintain for the community. It is much appreciated.
