### ISSUE TITLE
Use of EditorGuidelines interferes VS2022's ability to redraw text with color when working in C++

### ISSUE THREAD

**Issue by Warsen** [pharring/EditorGuidelines#129]
I've used your extension for a very long time over multiple versions of Visual Studio community editions (at least since 2017). I am usually working with C#, but occasionally I'd work on a project with C++. Something that has annoyed me ever since MS implemented editor colors in C++ is that I would cut and paste a block of code and that pasted code would appear black--not colored like the rest of the file I'm working on. If I would scroll away from the code, and then scroll back to it, then it would be colored properly.

I always thought this was some kind of mistake that MS made in the way that they refresh/redraw the page you're looking at in the editor after pasting/typing, and that it only happens with C++ because this is completely not an issue in C#. However, today I decided to disable EditorGuidelines and then I noticed this issue doesn't happen without the extension.

Please investigate this and see if you haven't made a mistake in how the editor guideline gets drawn. For recreating the issue, I don't know what else to say other than it happens when I'm working in C++, I have 1 editor guideline at 120 characters, there are few circumstances where your text would appear black, but notably it happens with paste operations.

**Comment by pharring** [comment]
Thanks for the report. I'll try and repro it.

**Comment by Warsen** [comment]
My sincere apologies, just after writing this up, it seems I can still still recreate the issue regardless of whether I have the extension enabled or not. It really might not be an issue with your extension. I'm sorry, I had played around with it for around an hour before committing to making a thread, and then only afterwards I got it to happen without.

**Comment by pharring** [comment]
@Warsen, no worries. Will close this issue for now.

**Comment by Warsen** [comment]
I'd recommend putting this on hold, until I can verify it really is happening or not. Again, I'm so sorry to bring this up. Thanks
