### ISSUE TITLE
Not Working - Globally ????

### ISSUE THREAD

**Issue by aspiecoder** [pharring/EditorGuidelines#130]
Is there a way to have it use a global setting?  

# Explicitly empty global editorconfig file to ensure we aren't accidentally applying unexpected rules to interactive documents
global = true

[*.cs]
guidelines = 80, 120

[*]
# Named color format
guidelines_style = 1px dotted black

[*.cs]
# ARGB color format (red with 25% opacity)
guidelines_style = 2.5px solid 40ff0000

I put this in my .editorconfig located here:

C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\VBCSharp\LanguageServices\InteractiveHost\Core

and here too:

C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\VBCSharp\LanguageServices\InteractiveHost\Desktop

It doesn't show up in my .cs files when I edit them.  Am I not using this right?

**Comment by pharring** [comment]
Those directories under "C:\Program Files" are the wrong locations for .editorconfig

See https://learn.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022#file-hierarchy-and-precedence

**Comment by pharring** [comment]
@aspiecoder I know this is an old issue. I hope the documentation link I gave helps. If you're still having problems, please re-open this issue with more info.
