### ISSUE TITLE
Refresh .csproj files

### ISSUE THREAD

**Issue by pharring** [pharring/EditorGuidelines#16]
Update the .csproj files by recreating them in VS 2017.
The current .csproj files are very old (dating back to VS 2010) and have accumulated a lot of 'junk'.
I've moved development exclusively to VS 2017 now, so there's no need to support _building_ on old VS versions.

* Recreate the .csproj files.
* Use PackageReference instead of packages.config

Investigate using .NET SDK-style projects too.

**Comment by sharwell** [comment]
Let me know if you'd like any assistance here
