### ISSUE TITLE
Feature request: horizontal “separator between methods”

### ISSUE THREAD

**Issue by HamRusTal** [pharring/EditorGuidelines#18]
[“Productivity Power Tools 2015”](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.ProductivityPowerTools2015) had the “Structure Visualizer” sub-extension which could show, among others, _separator between methods_. While Visual Studio 2017 incorporated one (main?) feature of the sub-extension (_structure guide lines_) the [“Productivity Power Tools 2017/2019”](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.ProductivityPowerPack2017) no longer includes the said sub-extension, so the “separator between methods” got lost.
Given that “Editor Guidelines” implements a visually related feature also previously part of “Productivity Power Tools”, this is IMHO quite a natural extension to add the missing “separator between methods” feature to.

![image](https://user-images.githubusercontent.com/29237693/51324692-6ab4a000-1a7c-11e9-86b9-55dd4e7414c4.png)

**Comment by pharring** [comment]
Thanks for the suggestion. I will see if I can find out how the method separator worked. It might be based off outlining information -- which would make an implementation somewhat easier than trying to do syntax parsing on the buffer content itself (which, of course gets us into language-specific code).

**Comment by HamRusTal** [comment]
> Does that do what you want?
I was just going to mention that option and you did it first.  :)
Unfortunately that option is of no use to me as I'm coding in C++. Yet top-level outlining-based implementation would be perfectly fine for me.

**Comment by pharring** [comment]
I'm not going to work on this feature.
