### ISSUE TITLE
Wrong Z-order causes the guide lines to be overdrawn by ReSharper's Current Line highlight and VS's built-in current outlining block highlight

### ISSUE THREAD

**Issue by HamRusTal** [pharring/EditorGuidelines#19]
Please see the brief discussion with one of ReSharper developers (who implemented some editor adornments) [starting at this comment](https://youtrack.jetbrains.com/issue/RSCPP-25213#focus=streamItem-27-3260374-0-0) (you might wish to choose “Sort: oldest first” in the “Activity settings” drop-down menu on the right).

It might become especially troublesome if some guide lines (e.g. indented ones) are displayed for the current line only in future.

**P.S.**
Here is how it looks (with an artificially narrow text):
![image](https://user-images.githubusercontent.com/29237693/51537237-079d8180-1e5f-11e9-8a5e-0665c76faebc.png)

**P.P.S.**
The guide line is also overdrawn by _VS's built-in_ current outlining block highlight on mouse-over:
![image](https://user-images.githubusercontent.com/29237693/51573316-d3a37a00-1eb9-11e9-9ae7-e84104300613.png)

**Comment by pharring** [comment]
What do you propose?

**Comment by HamRusTal** [comment]
> What do you propose?

I suggest putting the guide line adornment layer above the text layer, so that the adornment will overdraw the current line highlight. It will not hurt the text readability I believe as the line is thin and dotted.
