### ISSUE TITLE
Make guidelines configurable per solution

### ISSUE THREAD

**Issue by dotnetjunkie** [pharring/EditorGuidelines#2]
Guidelines are currently configured globally per version of Visual Studio. Guidelines however are often used as a visual aid for developers to conform to maximum line length coding convention. Such convention tends to change from project to project. It would therefore be really beneficial to be able to be able to configure guidelines on per-solution basis, ideally by using a config file in the solution directory. Having a config file in the solution directory is ideal, because it means that all developers working with that code base automatically get this setting.

**Comment by pharring** [comment]
Thanks for the suggestion. It's something that's been requested a number of times. Some people want different settings for different file extensions too.

For per-solution settings, I wonder if .editorconfig could be used. I'll have to research the APIs around reading editorconfig.

**Comment by pharring** [comment]
Yes, it looks like .editorconfig will work here -- at least on VS 2017 and above.

**Comment by pharring** [comment]
I tested in VS 2015 and it works, so I'm merging now.
It'll be in the next release.
