### ISSUE TITLE
Support editorconfig `max_line_length` setting.

### ISSUE THREAD

**Issue by hannni** [pharring/EditorGuidelines#26]
Editorconfig has a [`max_line_length`](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#supported-by-a-limited-number-of-editors) setting which some editors/formatters use for wrapping text.

The EditorGuidelines-Plugin could also read this setting apart from its own `guidelines` setting.

**Comment by pharring** [comment]
Thanks for the tip. It's a good suggestion.

**Comment by pharring** [comment]
If someone wants to take a look, the code that parses guideline values from .editorconfig is in UpdateGuidelinesFromCodingConventionsAsync https://github.com/pharring/EditorGuidelines/blob/master/src/ColumnGuide/ColumnGuide.cs#L239

For now, I suggest we treat "max_line_length" just like any other guideline and merge its setting in with our own guidelines. I presume "max_line_length" is and our guideline settings are aligned (i.e. the guideline goes to the right of the given value; so a max-line-length of zero would be hard up against the left-hand edge and probably useless)

**Comment by pharring** [comment]
I'm starting work on this today
