### ISSUE TITLE
.editorconfig guidelines in [*.{ext, ext2, ...}] files don't work

### ISSUE THREAD

**Issue by DubbleClick** [pharring/EditorGuidelines#37]
This is possibly only VS 2019, but while using 

```
[*]
guidelines = 80
```

works just fine,

```
[*.{php, js}]
guidelines = 80, 100
```

has no effect.

**Comment by pharring** [comment]
Try removing the space before `js`.

**Comment by DubbleClick** [comment]
Oh, sorry, that was just manually typed in here. There are no spaces in my actual .editorconfig

**Comment by pharring** [comment]
It works for me. Can you give a more complete repro? Are the php/js files part of a project or just loose files?

**Comment by DubbleClick** [comment]
Part of a project, here's a quick overview:
![image](https://user-images.githubusercontent.com/7896469/56468085-9eaab300-6427-11e9-80de-850ecb09e40d.png)

**Comment by DubbleClick** [comment]
Here's a php file opened: 
![image](https://user-images.githubusercontent.com/7896469/56468110-f0533d80-6427-11e9-90f4-8e1c28ca9cd7.png)

Same thing goes for vue files. Other file extensions have a guideline at 80.

I just noticed that .js files do indeed have the lines at 80 and 100 though:
![image](https://user-images.githubusercontent.com/7896469/56468138-4627e580-6428-11e9-92a2-3666abdc166f.png)

**Comment by DubbleClick** [comment]
If I manually add guidelines in .php/.vue files, they work just fine.

**Comment by DubbleClick** [comment]
Oh, reproduction is easy, by the way. Just create a new Basic Vue JS Project, add an editorconfig, configure guidelines in it and watch them being displayed in the .js, but not in the .vue file.

**Comment by pharring** [comment]
Thanks for the additional information. I'll try again to get a local repro.

BTW, I did find what I consider to be a bug with the .editorconfig mechanism -- at least in VS2019. It can sometimes stop sending change notifications. That makes experimenting with .editorconfig frustrating. Once it gets in that state, you have to restart the whole IDE (not just unload/reload the solution) before the notifications resume.

**Comment by DubbleClick** [comment]
Yes, I've had that in VS 2017 too. Not sure what triggered it, it seemed to happen randomly.

**Comment by pharring** [comment]
Are you using the "PHP Tools for Visual Studio" from Devsense? (If so, I'll download the free trial to try and repro)

**Comment by DubbleClick** [comment]
Yes, that's the php/twig extension. For .vue files it also haplens on a vanilla installation of VS.

**Comment by pharring** [comment]
I can repro this now with .vue and .html files. PHP is fine for me, BTW, but anything that's based on the HTML editor doesn't seem to respect guidelines. The HTML editor _does_ respect other .editorconfig settings like indent_size, so it's not like .editorconfig is ignored completely. I'll debug it some more.

**Comment by pharring** [comment]
Think I've figured it out. Need to work a bit harder to find the ITextDocument from the HTML IWpfTextView.

**Comment by pharring** [comment]
@DubbleClick thanks for the bug report. It was good to track this down and fix it because I'm sure other people have run into it. I'll push out the fix in a new release today.

**Comment by DubbleClick** [comment]
Awesome, thanks for the quick fix!
