### ISSUE TITLE
Default guidelines

### ISSUE THREAD

**Issue by josh-endries** [pharring/EditorGuidelines#4]
Two feature requests:

1. I was disappointed to find that there aren't any default guidelines, at least not that I could find (only the file context menu, which doesn't seem like it would remain for my next solution/project). It would be nice to be able to add a default guideline that was always available.

2. For years I've wanted dynamic guidelines for comments (or all text, if that's easier). "Dynamic" meaning the guidelines start at the line's indentation. I.e., if your comment is indented, the beginning of the guideline is as well. It would help a lot for making readable comments that are nested in methods or statements and/or automatically wrapping comments (via other extensions) while maintaining the same width when indented, instead of squishing nested/intended comments when wrapped at the "standard" 80 characters.

**Comment by pharring** [comment]
@josh-endries Thanks for the suggestions. I think each has merit and they're worth discussing separately. But please split this into two separate issues. Let's keep this one (edit the title and description) for the "default guidelines" and please create a new issue for "dynamic guidelines".

**Comment by fzzzt** [comment]
I moved the dynamic idea into #10. I can't figure out how to change this issue's name, though...

**Comment by pharring** [comment]
@josh-endries thanks for the suggestion. Guidelines are "global" -- once you set them in one text view, they'll show up in every other text view. And they persist across sessions. Are you perhaps thinking of a feature like #2 ?

**Comment by pharring** [comment]
I think this (default guidelines) is covered by the .editorconfig support. Please re-open if you have any further suggestions for this feature.
