### ISSUE TITLE
Port icons from Power Tools extension

### ISSUE THREAD

**Issue by pharring** [pharring/EditorGuidelines#49]
According to a review on the Marketplace, the Power Tools extension had
> up-to-date VS2017-style icons (this extension still uses old-school colored ones which look bad on a dark theme).

I believe this is referring to the icons on the context menu commands.
See if we can locate the icons used in Power Tools and port them over.
(May need to seek permission from the current Power Tools owners or find alternatives)

**Comment by RayKoopa** [comment]
Hey there, thanks for tracking this.

Yeah, I indeed meant the context menu icons with this. This is how they look with a dark theme in the Power Tools version in 2017 and this extension:
![image](https://user-images.githubusercontent.com/9631152/59472307-39c77400-8e3e-11e9-9292-73991d392fe6.png)
![image](https://user-images.githubusercontent.com/9631152/59472319-45b33600-8e3e-11e9-8823-447b28ead19b.png)

I updated my review on the gallery according to your reply. Speaking of the context menu, I also wondered if an entry to change the guideline color (as in the Power Tools version) should be added to make that feature more discoverable.

**Comment by pharring** [comment]
I located the icons from PPT. Need to check with the current owners if I have permission to use them.

**Comment by pharring** [comment]
See #50 for bringing back "Guideline Color..."

**Comment by pharring** [comment]
Got permission to use the icons. I should have time to push out an update this weekend.

**Comment by RayKoopa** [comment]
Excellent! I'll update my review when it's out.

**Comment by pharring** [comment]
Release 2.2.4 with the updated icons is in the Marketplace now.
