### ISSUE TITLE
Guidlines flyout missing

### ISSUE THREAD

**Issue by AndersBillLinden** [pharring/EditorGuidelines#5]
I have installed editor guidelines in Visual studio 2015 professional.
Earlier, I have not had any problems finding the guidlines flyout in the text editor right click menu, but this is all I get now:

![2018-08-08 13_55_22-](https://user-images.githubusercontent.com/1017466/43835651-f9bd725c-9b12-11e8-9577-58f7422188ca.png)

**Comment by AndersBillLinden** [comment]
Hm, getting it sometimes... maybe its resharper that disturbs that menu from populating...

**Comment by pharring** [comment]
@AndersBillLinden sorry for not replying until now. Is it still a problem for you?
Anyone else seeing this with Resharper?

**Comment by AndersBillLinden** [comment]
I am getting the Guidelines flyout now, it also seems like this is one of the extensions that are automatically updating theirselves, something I have not approved. The version I run now is 2.0.4. I am sorry to say that I did not check the version before, when I reported this issue. Should we close this?

**Comment by pharring** [comment]
Thanks for the reply. I will close this.
The automatic updating is on by default, but you can stop it by unchecking the option in "Tools/Extensions and Updates".
![image](https://user-images.githubusercontent.com/9952654/49849413-4800de80-fd8e-11e8-8671-c75471469cc8.png)
