### ISSUE TITLE
How to I configure default column?

### ISSUE THREAD

**Issue by NDelt** [pharring/EditorGuidelines#55]
Is there any way to configure default guideline column without .editorconfig file?
I can't find related settings in `Tools | Options` menu.

**Comment by pharring** [comment]
Yes. Please see https://github.com/pharring/EditorGuidelines#getting-started
To recap, there are two ways:
1. Context (right-click) menu in the editor window.
2. Edit.AddGuideLine from the Command tool window.

**Comment by NDelt** [comment]
I missed this point: `line will be drawn at the same position as the caret`
Thanks.
