### ISSUE TITLE
Setting guidlines in .editorconfig doesn't fully work

### ISSUE THREAD

**Issue by shadow-cs** [pharring/EditorGuidelines#59]
I'm using guidelines set by `.editorconfig`:

```ini
[*.cs]
max_line_length = 120
guidlines = 80, 120
```

However I only see the guideline on position `120`.

If I comment out `max_line_length` I see it on position `80` only. I'm (almost 😉) sure it did work correctly at some point but I noticed this behavior only recently.

There is clearly some interaction between setting both `max_line_length` and `guidlines`. IMHO `guidlines` should take precedence (or `max_line_length` should be added to `guidlines` but certainly not replace it).

Version: `2.2.4`
Visual Studio 2019 version: `16.2.4` (I do have ReSharper installed)

**Comment by pharring** [comment]
Thanks for the bug report, @shadow-cs. I could not reproduce this myself. I see both guidelines.

However, I did notice that "live" updating of .editorconfig settings was broken. (This has been a problem for a while and I'll look into it.)

Does the problem persist after closing and re-opening your solution? Can you be sure that your .editorconfig is being used? (e.g. make another change like "indent_size" and see if it has an effect).

**Comment by pharring** [comment]
FYI: Live updates to .editorconfig are broken when you edit it from within Visual Studio. If you use another editor (e.g. notepad, VSCode or even another instance of Visual Studio) to edit .editorconfig, then live updates work. That seems like a bug; I will enter a Visual Studio feedback item about it.

**Comment by pharring** [comment]
On the Live updates: It's more subtle than that. Sometimes it works; sometimes it doesn't. If I can figure out the pattern, I'll report it to the Feedback Hub.

In any case, _this_ issue is about mixing `max_line_length` with `guidelines`, and that should certainly work. I can't repro the bug myself.

**Comment by shadow-cs** [comment]
@pharring thanks for a quick response. I forgot to mention I did restart VS each time I made changes (I did notice the warning about VS not handling live changes properly in other issues when I was looking for duplicates).

Other changes from the `.editorconfig` are reflected properly (after restarting VS 😉).

I did notice `.editorconfig` (or the editing experience in general) has been a little fuzzy lately, I'm getting warnings about mixed tabs and spaces which I have to correct manually, but the editor itself respects `indent_size` properly just newly typed code breaks indentation (not sure why though).

Please send the link to feedback here, I'll certainly upvote.

Is there anything I can try to help you figure this out? I already tied disabling all other extensions but it didn't fix the issue.

This is my `.editorconfig` file: [editorconfig.txt](https://github.com/pharring/EditorGuidelines/files/3599918/editorconfig.txt)

**Comment by pharring** [comment]
Mystery solved: I just noticed a typo in your .editorconfig (and throughout this issue, in fact!)
You're missing the 'e' in the middle of guid**e**lines.

If you were seeing a guideline at column 80 after removing `max_line_length` then I suspect it's falling back to the global guideline setting (without using .editorconfig). You can remove that by doing "Edit.RemoveGuideline 80" from the command window.

**Comment by shadow-cs** [comment]
🤦‍♂ I just copy-pasted the same issue over and over again. Thanks a lot and sorry for bothering you with such idiotic error.
