### ISSUE TITLE
Enhancement - Allow for multiple guideline styles

### ISSUE THREAD

**Issue by szalkerous** [pharring/EditorGuidelines#64]
It would be great if we could define a few different styles of guidelines... pattern and color specifically.

Even if there was a hardcoded amount of 3, that would be more than useful.

This way I could color a green guideline to indicate the maximum width of comments, and a red guideline to indicate maximum width of code to assist with code formatting.

Thanks for considering!

**Comment by pharring** [comment]
Thanks for the suggestion. I think it's a good idea.

I believe the code change to support different colors and styles for each guideline is pretty straightforward.

A full-featured UI for setting the colors and styles on each guideline can wait, but we should start by defining an extended syntax for .editorconfig.

Current:

```ini
guidelines = 80, 120, 132
guidelines_style = 1px dotted black
```
Specifies three guides, but they're all the same style.

Proposed:
```ini
guidelines = 80, 120 2.5px dashed 40ff0000, 132 1px solid green
guidelines_style = 1px dotted black
```
Basically, allow the style to be specified alongside the column number. If specified, it overrides the default style (specified by guidelines_style). The separator is the comma.

The only slight problem with this is that the current scheme allows a space as a separator for guidelines (see [ParseGuidelinePositionsFromCodingConventions](https://github.com/pharring/EditorGuidelines/blob/master/src/ColumnGuide/Parser.cs#L23)), and we don't want to break existing valid configurations. However, I think it's easy to keep it compatible.

**Comment by pharring** [comment]
This is in the 2.2.5 release
