### ISSUE TITLE
Cannot find setup engine instance

### ISSUE THREAD

**Issue by gurrenm3** [pharring/EditorGuidelines#68]
Tried installing a few different versions of this and got the same error each time. "Cannot find setup engine instance". Here is the install log: https://pastebin.com/NaSZ55QP

**Comment by pharring** [comment]
I think this indicates a problem with the VSIX Installer, not necessarily with this extension.
Can you please use the "Report a Problem..." feature in Visual Studio itself to report this:
![image](https://user-images.githubusercontent.com/9952654/80035547-11b89080-84a5-11ea-8d20-a3b364c9a299.png)

Also, I found this:
https://stackoverflow.com/questions/54382367/visual-studio-extension-installation-cannot-find-setup-engine-instance

**Comment by gurrenm3** [comment]
Thanks for the help :D
I was able to get it working
