### ISSUE TITLE
Remove support for Dev11 (VS 2012)

### ISSUE THREAD

**Issue by pharring** [pharring/EditorGuidelines#8]
I'm thinking of simplifying the test matrix by removing support for VS 2012.
This will also simplify the build.
I need to check whether the Marketplace will continue to serve up old versions for VS 2012 users.
This is not a final decision, but if anyone has an objection, here's the place to discuss.

**Comment by pharring** [comment]
I found out that the Marketplace doesn't have a history of old versions. So, if we want to continue support for VS 2012 users, we need to create a new VSIX identity "Editor Guidelines VS 2012" -- just like I did for VS 2010.

**Comment by pharring** [comment]
I checked telemetry for usage by VS Version and Dev 11 is around 2% of daily sessions. There are a few Dev 11 users on older versions, but most are staying current (which is surprising since Dev 11 didn't have auto-updating of VSIXes). They are surprisingly active users too - several sessions a day.

Here's my plan:
1. Add a warning UI for Dev 11 users that the current version is the last one to support them (ironically, Dev 11 doesn't don't support the Infobar control which would otherwise be ideal to render the UI)
2. Create a Dev11 branch in this repo. Set up a new build pipeline for pushes to that branch.
3. Make an "Editor Guidelines VS 2012" VSIX and publish it in the Marketplace with a new identity.
4. Upgrade support In "master" to Dev 11.

**Comment by sharwell** [comment]
I believe starting with 2012 (you'll want to check the exact version), you can specify different assemblies for different versions of Visual Studio. This would allow you to package a fixed older version of the assemblies in the VSIX file that load in 2012, and a second set of assemblies that load on newer versions.
