### ISSUE TITLE
Feature request: fixed horizontal guideline

### ISSUE THREAD

**Issue by Kizaemon** [pharring/EditorGuidelines#86]
Hi, I wonder if you can consider implementing this new feature?

I'm looking for a sticky overlayed guideline, which is affixed to the VS frame or MDI well.
This could be a thin transucent blue line, going from left to right over the whole editor area.
The key feature is that the line stays vertically fixed to the well at the same height for all documents, unmoved by vertical scroll.

The reason/usage:

I frequently need to remove duplicate code from multiple files.
I usually scroll the two documents vertially to the same screen position, alining the the lines which I want to compare.
Then I switch between the two documents repeatedly using the Ctrl+Tab.
Doing so I can quickly visually identify the sattle differences of the code or confirm that the code is exactly same.

Unfortunately VS does not have an integral scroll (using half-lines).
It takes me considerable time to align the lines of the two documents to be at the same physical location on the screen.

Having an fixed (but draggable) horizontal guidline will help alot.

**Comment by pharring** [comment]
Thanks for the suggestion, @Kizaemon.
The horizontal bar is a long way from the current functionality that Editor Guidelines provides, so at this time I won't implement it.

I admit I've often tried comparing two documents by Ctrl+Tab-ing between them. In case it helps, there's a command-line switch that compares two files and shows their differences. See: https://docs.microsoft.com/visualstudio/ide/reference/diff

> Unfortunately VS does not have an integral scroll (using half-lines).
It takes me considerable time to align the lines of the two documents to be at the same physical location on the screen.

I don't know if this is what you're looking for, but there are quite a few "smooth scroll" extensions already in the Visual Studio Marketplace: https://marketplace.visualstudio.com/search?term=smooth%20scroll&target=VS&category=All%20categories&vsVersion=&sortBy=Relevance
