### ISSUE TITLE
Package fails to load under VS2022 and VS2022 Preview

### ISSUE THREAD

**Issue by krazyplacebo** [pharring/EditorGuidelines#94]
I love this extension and have used it extensively under VS2019 Community Edition, but it fails to work for me under both VS2022 Community Edition and VS2022 Community Edition Preview.

When I right-click and try to add a guideline, I get a 'The EditorGuidelinesPackage did not load correctly' error. 
My ActivityLog.xml file shows:

SetSite failed for package [EditorGuidelinesPackage]Source: &apos;EditorGuidelines&apos; Description: Could not load file or assembly &apos;Microsoft.ApplicationInsights, Version=2.1.0.0

I have no idea of how I go about installing Microsoft.ApplicationInsights version 2.1.0.0

Any help or advice would be much appreciated. Many thanks.

**Comment by bddckr** [comment]
See #87. A workaround can be found in [this comment](https://github.com/pharring/EditorGuidelines/issues/87#issuecomment-965794495).

The linked VS bug ticket has been marked as fixed just yesterday, so fingers crossed it's soon fixed because of that 🤞

**Comment by krazyplacebo** [comment]
That workaround fixed it for me. Many thanks Chris!
