### ISSUE TITLE
Only one version attached to the tag

### ISSUE THREAD

**Issue by teeks99** [pharring/EditorGuidelines#98]
Apparently the 2022 version requires a different build, as there is a separate marketplace link:

*   [VS2012-VS2019 Marketplace](https://marketplace.visualstudio.com/items?itemName=PaulHarrington.EditorGuidelines)
*   [VS2022 Marketplace](https://marketplace.visualstudio.com/items?itemName=PaulHarrington.EditorGuidelinesPreview)

Based on the URLs that both of these point to, they both appear to be 2.2.8.

However, the GitHub [assets for the 2.2.8 tag](https://github.com/pharring/EditorGuidelines/releases/tag/2.2.8) only has one binary attached to it.

Looking at the SHA-256s of all three files, it appears to be the non-2022 version:

```
$ sha256sum EditorGuidelines_*
07edb314c8bd99c1596a17ce5994f7e712d7c15d570a537e7b6f9cacdedbc310  EditorGuidelines_Github2.2.8TagAsset.vsix
07edb314c8bd99c1596a17ce5994f7e712d7c15d570a537e7b6f9cacdedbc310  EditorGuidelines_MarketplaceExisting.vsix
34963a002f3dfbf8087b11788698e8f6cb4766d7349967825839a2e20aa3da9b  EditorGuidelines_MarketplacePreview.vsix
```

Could both binaries be uploaded with the github tag?

**Comment by pharring** [comment]
Updated for 2.2.8
It's a manual process for now.
