### ISSUE TITLE
not worker on vs2022.1

### ISSUE THREAD

**Issue by aengusjiang** [pharring/EditorGuidelines#99]
not work on vs2022.1, 
seem not load the extension
![image](https://user-images.githubusercontent.com/22406984/155457873-34b57b4f-7d2f-4708-ac03-7476bbb76c4a.png)

**Comment by alwinnat** [comment]
Hello, 
I have the same issue in Visual Studio Enterprise 2022 Version 17.1.0.  
Following the error entry of ActivityLog.xml:

> SetSite failed for package [EditorGuidelinesPackage]Source: 'EditorGuidelines' Description: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' at EditorGuidelines.EditorGuidelinesPackage.<InitializeAsync>d__4.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) at EditorGuidelines.EditorGuidelinesPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress) at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

**Comment by bddckr** [comment]
Please see the pinned issue #87.

**Comment by pharring** [comment]
The workaround is to run the "Visual Studio Installer", select "Modify" and add the "Developer Analytics" workload.
